package Interfaz;

import Administrador.Administrador;
import java.awt.Image;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import principal.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MAYKOL
 */
public class ventaCredito extends javax.swing.JFrame {

    /**
     * Creates new form ventaCredito
     */
    String cargo;
    public ventaCredito(String nombre_cargo) {
        
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        cargo=nombre_cargo;
        initComponents();
        this.setResizable(false);
        imagen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelCuota = new javax.swing.JLabel();
        labelEstadoVenta = new javax.swing.JLabel();
        labelDeudaVentaCredito = new javax.swing.JLabel();
        labelCI = new javax.swing.JLabel();
        textCI = new javax.swing.JTextField();
        textCuota = new javax.swing.JTextField();
        textEstadoVenta = new javax.swing.JTextField();
        textDeudaVentaCredito = new javax.swing.JTextField();
        botonNuevo = new javax.swing.JButton();
        botonConfirmar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        labelTitulo.setFont(new java.awt.Font("Eras Bold ITC", 1, 28)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("VENTA A CREDITO ");
        getContentPane().add(labelTitulo);
        labelTitulo.setBounds(300, 20, 398, 50);

        labelCuota.setFont(new java.awt.Font("Eras Bold ITC", 1, 20)); // NOI18N
        labelCuota.setText("Cuota:");
        getContentPane().add(labelCuota);
        labelCuota.setBounds(30, 140, 134, 35);

        labelEstadoVenta.setFont(new java.awt.Font("Eras Bold ITC", 1, 20)); // NOI18N
        labelEstadoVenta.setText("Estado Venta:");
        getContentPane().add(labelEstadoVenta);
        labelEstadoVenta.setBounds(30, 190, 190, 35);

        labelDeudaVentaCredito.setFont(new java.awt.Font("Eras Bold ITC", 1, 20)); // NOI18N
        labelDeudaVentaCredito.setText("Deuda Venta Credito:");
        getContentPane().add(labelDeudaVentaCredito);
        labelDeudaVentaCredito.setBounds(30, 240, 202, 35);

        labelCI.setFont(new java.awt.Font("Eras Bold ITC", 1, 20)); // NOI18N
        labelCI.setText("CI:");
        getContentPane().add(labelCI);
        labelCI.setBounds(30, 290, 134, 35);

        textCI.setFont(new java.awt.Font("Eras Bold ITC", 1, 15)); // NOI18N
        getContentPane().add(textCI);
        textCI.setBounds(320, 290, 440, 35);

        textCuota.setFont(new java.awt.Font("Eras Bold ITC", 1, 15)); // NOI18N
        getContentPane().add(textCuota);
        textCuota.setBounds(320, 140, 440, 35);

        textEstadoVenta.setFont(new java.awt.Font("Eras Bold ITC", 1, 15)); // NOI18N
        getContentPane().add(textEstadoVenta);
        textEstadoVenta.setBounds(320, 190, 440, 35);

        textDeudaVentaCredito.setFont(new java.awt.Font("Eras Bold ITC", 1, 15)); // NOI18N
        getContentPane().add(textDeudaVentaCredito);
        textDeudaVentaCredito.setBounds(320, 240, 440, 35);

        botonNuevo.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(botonNuevo);
        botonNuevo.setBounds(490, 380, 150, 50);

        botonConfirmar.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        botonConfirmar.setText("Confirmar");
        botonConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonConfirmarMouseClicked(evt);
            }
        });
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(botonConfirmar);
        botonConfirmar.setBounds(320, 380, 150, 50);

        botonCancelar.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCancelar);
        botonCancelar.setBounds(650, 380, 150, 50);

        pack();
    }// </editor-fold>                        

    private void botonConfirmarMouseClicked(java.awt.event.MouseEvent evt) {                                            
        
        recogerDatos();
                
    }                                           

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {                                           
        this.setVisible(false);
        registroCliente f=new registroCliente();
        f.setVisible(true);
    }                                          

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {                                               
        //this.setVisible(false);
        //PrincipalNuevo n= new PrincipalNuevo(cargo);       
    }                                              

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                              
         Object [] opciones ={"Aceptar","Cancelar"};
            int eleccion = JOptionPane.showOptionDialog(rootPane,"En realidad desea realizar cerrar la aplicacion","Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,null,opciones,"Aceptar");
                if (eleccion == JOptionPane.YES_OPTION)
                {
                 System.exit(0);
                }else{
                }        
    }                                             

    Administrador admin = Administrador.crearAdministrador("");
    Validacion validar = new Validacion();
    public void recogerDatos(){
        String Cuota= textCuota.getText();
        String EstadoVenta = textEstadoVenta.getText();
        String DeuVentCred=textDeudaVentaCredito.getText();
        String CI = textCI.getText();
        if(validar.CIValido(CI) && validar.esNumero(Cuota) && validar.esNumero(DeuVentCred) && validar.esPalabra(EstadoVenta))
            admin.ingresarVentaCredito(Integer.parseInt(Cuota), EstadoVenta, Integer.parseInt(DeuVentCred), Integer.parseInt(CI));
        else
           JOptionPane.showMessageDialog(null,"datos incorrectos");
         
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventaCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventaCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventaCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventaCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventaCredito("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonConfirmar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JLabel labelCI;
    private javax.swing.JLabel labelCuota;
    private javax.swing.JLabel labelDeudaVentaCredito;
    private javax.swing.JLabel labelEstadoVenta;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField textCI;
    private javax.swing.JTextField textCuota;
    private javax.swing.JTextField textDeudaVentaCredito;
    private javax.swing.JTextField textEstadoVenta;
    // End of variables declaration                   
    private JLabel fondos;
    private void imagen() {
        fondos = new JLabel(); 
        fondos.setBounds(0,0,1000,600);
        URL url=getClass().getResource("/Imagen/InterfazMejor.jpg");
        ImageIcon image=new ImageIcon(url);
        Icon icono = new ImageIcon(image.getImage().getScaledInstance(fondos.getWidth(), fondos.getHeight(), Image.SCALE_DEFAULT));
        fondos.setIcon(icono);
        fondos.repaint();
        this.getContentPane().add(fondos);
    }
}
